@base_url = http://localhost:3000

### GET Request
GET {{base_url}}/api/items

### POST Request
POST {{base_url}}/api/items
Content-Type: application/json

{  
  "username": "New-user-now-9",
  "displayName": "Twe-2"
}

### PUT Request
PUT {{base_url}}/api/items/651e3e38b0ce31abad07b399
Content-Type: application/json

{
  "username": "Updated Item-7",
  "displayName": "Twenty-five"
}

### DELETE Request
DELETE {{base_url}}/api/items/651622e10f5058f05cc478d2

